docs(switch): Revamp Overview
telerik/blazor-docs pull request #1055
Opened 2022-07-19 15:22 UTC by ntacheva

2022-07-20 14:25 UTC, dimodi commented on components/switch/overview.md
> +## Creating Switch for Blazor
```suggestion
## Creating Blazor Switch
```

2022-07-20 14:26 UTC, dimodi commented on components/switch/overview.md
> +1. Provide `Value` (one-way data binding) or `bind-Value` (two-way data binding) property
Or you can just say "Set the `Value` parameter to a `bool` property. It supports one-way or two-way binding."
```suggestion
1. Provide `Value` (one-way data binding) or `@bind-Value` (two-way binding) property
```

2022-07-20 14:30 UTC, dimodi commented on components/switch/overview.md
> +The Switch provides the following features to allow further customization of its behavior:
Also link the API page

2022-07-20 14:31 UTC, dimodi commented on components/switch/overview.md
> +| `Value` and `bind-Value` | `bool` or `bool?`| the value of the Switch.
@bind-Value is not a separate parameter that requires mentioning. "@bind" is a Blazor directive. We can specify that it supports two-way binding in the description.

2022-07-20 14:35 UTC, dimodi commented on components/switch/overview.md
> +<TelerikSwitch @bind-Value="@toggleSwitch" @ref="@TheSwitchRef" />
Should be `SwitchRef` - see the Docs & Demos Style Guide in the blazor repo wiki

2022-07-20 14:57 UTC, dimodi requested changes
Some comments related to consistency and docs coding style guide.

2022-07-20 15:33 UTC, ntacheva commented on components/switch/overview.md
> +1. Use the `TelerikSwitch` tag
I think `<Foo>` tag is better. Updated

2022-07-26 12:24 UTC, dimodi approved these changes

2022-07-26 12:52 UTC, merged