docs: introduced appearance articles from form, pager, toolbar
telerik/blazor-docs pull request #1256
Opened 2022-12-21 09:17 UTC by yanisslav

2022-12-22 07:50 UTC, svdimitr commented on components/form/appearance.md
> +    @ code{
This snippet will not compile, can you remove the space between `@` and `code`

2022-12-22 07:50 UTC, svdimitr commented on components/form/appearance.md
> +You can increase or decrease the size of the Form by setting the `Size` parameter to a member of the `Telerik.Blazor.ThemeConstants.Form.Size` class:
Maybe you can add some more information that the Size controls the padding for all form editors and buttons.

2022-12-22 07:50 UTC, svdimitr commented on components/form/appearance.md
> +| `Medium`   |`md`|
Add that `Medium` is the default size option.

Applies to all articles.

2022-12-22 07:50 UTC, svdimitr commented on components/form/appearance.md
> +| `Medium`   |`md`|
Add that `Medium` is the default size option.

Applies to all articles.

2023-01-12 09:55 UTC, ntacheva commented on components/form/appearance.md
> +If the size option is not specified, it is set to `Medium` by default.
Look how the default options is specified in other appearance articles - e.g. https://docs.telerik.com/blazor-ui/components/autocomplete/appearance#fillmode.

Listed in the table for better visibility. Let's keep that approach for consistency. Applies to all articles.

2023-01-12 10:04 UTC, ntacheva commented on components/form/appearance.md
> +>The `Size` configuration of the Form affects the padding of all the editors and buttons.
Move that not after the first paragraph to provide the main information for the parameter first and then list the specifics.

2023-01-12 10:05 UTC, ntacheva requested changes
Listed in the comments above.

2023-01-12 10:44 UTC, ntacheva commented
Link the "Appearance" articles in the "Overview" of the corresponding components. Reference: http://localhost/blazor-ui/components/autocomplete/overview#styling-and-appearance

2023-01-13 11:17 UTC, ntacheva commented on components/form/overview.md
> +## Styling and Appearance
Look how this section is styled and positioned in other components' "Overview" articles. Let's keep the same formatting and position for consistency. Applies to all articles.

2023-01-13 11:19 UTC, ntacheva requested changes
Apologies for not mentioning this earlier - we need to link the demo pages from the "See also" section in all three articles.

2023-01-16 08:55 UTC, ntacheva commented on components/form/overview.md
> +## Styling and Appearance
```suggestion
### Styling and Appearance
```

2023-01-16 08:56 UTC, ntacheva commented on components/toolbar/overview.md
> +## Styling and Appearance
```suggestion
### Styling and Appearance
```

2023-01-16 08:58 UTC, ntacheva approved these changes

2023-01-16 09:03 UTC, merged