docs(grid, treelist): linked popup templates articles in customization
telerik/blazor-docs pull request #1475
Opened 2023-05-30 05:19 UTC by yanisslav

2023-05-30 06:29 UTC, yordan-mitev commented on components/grid/editing/popup.md
> +### PopUp Form Customization
```suggestion
### Popup Form Customization
```

2023-05-30 06:29 UTC, yordan-mitev commented on components/grid/editing/popup.md
Could you please replace "PopUp" with "Popup" in the entire article?

2023-05-30 06:29 UTC, yordan-mitev commented on components/grid/templates/popup-form-template.md
> +>When a `FormTemplate` is declared, the Grid no longer handles the Update and Cancel operations.
```suggestion
>When you declare a `FormTemplate`, the Grid no longer handles the Update and Cancel operations.
```

2023-05-30 06:29 UTC, yordan-mitev commented on components/treelist/templates/popup-form-template.md
> +>When a `FormTemplate` is declared, the TreeList no longer handles the Update and Cancel operations.
```suggestion
>When you declare a `FormTemplate`, the TreeList no longer handles the Update and Cancel operations.
```

2023-05-30 06:29 UTC, yordan-mitev commented on components/treelist/editing/popup.md
Please replace "PopUp" with "Popup" in the entire document.

2023-06-02 12:02 UTC, ntacheva commented
- [ ] Add a TOC with links at the beginning of the Customization section - it is long and the last customization options are not easily visible.

2023-06-02 12:11 UTC, ntacheva requested changes
Listed above.

2023-06-02 15:22 UTC, ntacheva commented on components/grid/templates/popup-form-template.md
> +You can use the `Context` attribute of the `<FormTemplate>` tag to set the name of the context variable. The context variable is of type `object` and can be cast to the model type to which the grid i
```suggestion
You can use the `Context` attribute of the `<FormTemplate>` tag to set the name of the context variable. The context variable is of type `object` and can be cast to the model type to which the Grid is bound.
```

2023-06-02 15:23 UTC, ntacheva commented on components/treelist/templates/popup-form-template.md
> +With the `FormTemplate` feature, you can customize the appearance and content of the create/edit Popup window of the TreeList. To set it, provide contents to the `<FormTemplate>` inner tag of the `<T
```suggestion
With the `FormTemplate` feature, you can customize the appearance and content of the create/edit Popup window of the TreeList. To set it, provide contents to the `<FormTemplate>` inner tag of the `<TreeListPopupEditFormSettings>`.
```
```suggestion
With the `FormTemplate` feature, you can customize the appearance and content of the create/edit Popup window of the TreeList. Declare the desired custom content inside the `<FormTemplate>` inner tag of the `<TreeListPopupEditFormSettings>`.
```

2023-06-02 15:23 UTC, ntacheva approved these changes

2023-06-05 04:58 UTC, merged