docs(input validation): fix examples for MaskedTextbox and Slider
telerik/blazor-docs pull request #1624
Opened 2023-09-08 10:12 UTC by YanushevGeorgi

Note to external contributors: make sure to sign our Contribution License Agreement (CLA) for Blazor UI first:

https://forms.office.com/Pages/ResponsePage.aspx?id=Z2om2-DLJk2uGtBYH-A1NbWxVqugKN5DvVp8I-1AgOBURFBVSkwyMlA1TkFDVFdMNU1aM1o1UlZQOC4u

2023-09-08 11:02 UTC, dimodi commented on common-features/input-validation.md
> +        height: 60px
If the purpose of this CSS rule is to increase the space between the Sliders and the labels, there are better ways to do that, which do not include our internal CSS classes - for example, add margins to the custom labels.

2023-09-08 11:45 UTC, dimodi commented on common-features/input-validation.md
> +        <TelerikFloatingLabel Text="Credit Card*:">
We don't use `*` for required fields anywhere.

```suggestion
        <TelerikFloatingLabel Text="Credit Card:">
```

2023-09-08 11:45 UTC, dimodi requested changes
Replace the Slider height with some other CSS, which doesn't require knowledge about our components' CSS classes.

2023-09-13 12:30 UTC, yordan-mitev reviewed
✨

2023-09-15 07:21 UTC, dimodi commented on common-features/input-validation.md
> +        margin-top: 15px
Always use `;`

```suggestion
        margin-top: 1em;
```

2023-09-15 07:21 UTC, dimodi approved these changes

2023-09-18 05:46 UTC, merged