[4.6] docs(a11y): add grid and treeview examples that cover latest wcag gui…
telerik/blazor-docs pull request #1668
Opened 2023-10-09 15:24 UTC by xristianstefanov

Related to: https://github.com/telerik/blazor/issues/7199.

2023-10-09 18:08 UTC, dimodi commented on components/grid/accessibility/overview.md
> +<style>
Move the style tag after the component that needs it.

2023-10-09 18:09 UTC, dimodi commented on components/grid/accessibility/overview.md
> +@code {
Use `private` accessors, except for classes, according to our code style.

2023-10-09 18:10 UTC, dimodi commented on components/treeview/accessibility/overview.md
> +                Expanded = true
This looks like an outdated example, because the TreeView no longer uses `Expanded` model properties.

2023-10-09 18:11 UTC, dimodi commented on components/treeview/accessibility/overview.md
> +    private TelerikContextMenu<ContextMenuItem> ContextMenu { get; set; }
Use consistent property and method accessors (`private`).

2023-10-09 18:12 UTC, dimodi requested changes
* Follow the Docs and Demos Code Style in the `blazor` repo wiki.
* Remove the obsolete `Expanded` property for the TreeView.

2023-10-10 08:53 UTC, yordan-mitev approved these changes

2023-10-10 14:23 UTC, dimodi approved these changes

2023-10-10 14:27 UTC, merged