chore(dropdowns): link custom filtering kb
telerik/blazor-docs pull request #1730
Opened 2023-11-03 14:21 UTC by ntacheva

2023-11-03 15:51 UTC, dimodi requested changes
Two adjacent links that point to the same location look strange. This setup may either trigger a "WTF" reaction or the reader can assume one of the links is wrong. Consider merging.

2023-11-07 08:35 UTC, yordan-mitev reviewed
Use title case in the anchor links, for example, "Custom Filtering by Multiple Fields".

2023-11-15 13:19 UTC, ntacheva commented on components/autocomplete/filter.md
> +* [Custom filtering by multiple fields]({%slug dropdowns-kb-search-in-multiple-fields%})
```suggestion
* [Custom Filtering by Multiple Fields]({%slug dropdowns-kb-search-in-multiple-fields%})
```

2023-11-15 13:20 UTC, ntacheva commented on components/combobox/filter.md
> +* [Custom filtering by multiple fields]({%slug dropdowns-kb-search-in-multiple-fields%})
```suggestion
* [Custom Filtering by Multiple Fields]({%slug dropdowns-kb-search-in-multiple-fields%})
```

2023-11-15 13:20 UTC, ntacheva commented on components/combobox/filter.md
> +* [Filter by field that is not the TextField]({%slug dropdowns-kb-search-in-multiple-fields%})
```suggestion
```

2023-11-15 13:21 UTC, ntacheva commented on components/dropdownlist/filter.md
> +* [Custom filtering by multiple fields]({%slug dropdowns-kb-search-in-multiple-fields%})
```suggestion
* [Custom Filtering by Multiple Fields]({%slug dropdowns-kb-search-in-multiple-fields%})
```

2023-11-15 13:21 UTC, ntacheva commented on components/dropdownlist/filter.md
> +* [Filter by field that is not the TextField]({%slug dropdowns-kb-search-in-multiple-fields%})
```suggestion
```

2023-11-15 13:21 UTC, ntacheva commented on components/multicolumncombobox/filter.md
> +* [Custom filtering by multiple fields]({%slug dropdowns-kb-search-in-multiple-fields%})
```suggestion
* [Custom Filtering by Multiple Fields]({%slug dropdowns-kb-search-in-multiple-fields%})
```

2023-11-15 13:21 UTC, ntacheva commented on components/multicolumncombobox/filter.md
> +* [Filter by field that is not the TextField]({%slug dropdowns-kb-search-in-multiple-fields%})
```suggestion
```

2023-11-15 13:22 UTC, ntacheva commented on components/multiselect/filter.md
> +* [Custom filtering by multiple fields]({%slug dropdowns-kb-search-in-multiple-fields%})
```suggestion
* [Custom Filtering by Multiple Fields]({%slug dropdowns-kb-search-in-multiple-fields%})
```

2023-11-15 13:22 UTC, ntacheva commented on components/multiselect/filter.md
> +* [Filter by field that is not the TextField]({%slug dropdowns-kb-search-in-multiple-fields%})
```suggestion
```

2023-11-15 15:09 UTC, dimodi approved these changes

2023-11-15 15:09 UTC, merged