[5.1]docs(contextmenu): item render event documentation
telerik/blazor-docs pull request #1810
Opened 2023-12-11 15:38 UTC by YanushevGeorgi

Related to: [#8166](https://github.com/telerik/blazor/issues/8166)

2023-12-12 10:54 UTC, yordan-mitev approved these changes

2023-12-12 10:54 UTC, yordan-mitev commented on components/contextmenu/events.md
> +This article describes the events available in the Telerik Context Menu for Blazor:
```suggestion
This article describes the events generated by the Telerik Context Menu for Blazor:
```

2023-12-14 14:23 UTC, dimodi commented on components/contextmenu/events.md
> +This article describes the events generated by the Telerik Context Menu for Blazor:
```suggestion
This article describes the events that are fired by the Telerik Context Menu for Blazor:
```

2023-12-14 14:24 UTC, dimodi commented on components/contextmenu/events.md
> +* [`OnItemRender`](#onitemrender)
The events are sorted alphabetically, which is OK, but then the sections are not.

2023-12-14 14:25 UTC, dimodi commented on components/contextmenu/events.md
> +>caption Customizing the appearance of the Context Menu items.
```suggestion
>caption Using OnItemRender to customize the appearance of the Context Menu items.
```

2023-12-14 14:25 UTC, dimodi commented on components/contextmenu/events.md
> +<TelerikContextMenu Data="@MenuItems" Selector=".context-menu-target" OnItemRender="@RenderItemHandler">
Consider multi-line declaration

2023-12-14 14:26 UTC, dimodi commented on components/contextmenu/events.md
> +        args.Class = "orange";
Use a conditional statement to style only 1-2 items, or use several classes and colors.

2023-12-14 14:27 UTC, dimodi requested changes
* Sort event sections alphabetically
* Style one item only, or use different colors

2023-12-19 16:05 UTC, ntacheva commented on components/contextmenu/events.md
> +    public List<ContextMenuItem> MenuItems { get; set; }
```suggestion
    private List<ContextMenuItem> MenuItems { get; set; }
```
According to code style

2023-12-21 07:13 UTC, dimodi commented on components/contextmenu/events.md
> +        args.Class = item.Items==null ? "orange" : "lime";
```suggestion
        args.Class = item.Items == null ? "orange" : "lime";
```

2023-12-21 07:13 UTC, dimodi approved these changes

2023-12-21 08:31 UTC, merged