docs(common): update intro docs to mention trial watermark and banner
telerik/blazor-docs pull request #1838
Opened 2024-01-05 17:51 UTC by ntacheva

2024-01-09 08:52 UTC, dimodi commented on introduction.md
> +UI for Blazor is a commercial UI library. You are welcome to explore its full functionality and get technical support from the team when you register for a free 30-day trial. After the trial period e
Consult
1.2.5. Limitations on Evaluation or Trial Licenses
of the license agreement
https://www.telerik.com/purchase/license-agreement/blazor-ui

After the trial period expires, the components should not be used. We can avoid disucssing this here if we just mention that the trial version has watermark and banner.

2024-01-09 08:53 UTC, dimodi requested changes
We should not advertise that the product works after the trial period expires.

2024-01-09 16:10 UTC, dimodi commented on introduction.md
> +UI for Blazor is a commercial UI library. You are welcome to explore its full functionality and get technical support from the team when you register for a free 30-day trial. After the trial period e
@ikoevska Actually, the trial watermark and banner will appear during the trial period as well.

2024-01-10 16:46 UTC, ntacheva commented on introduction.md
> +UI for Blazor is a commercial UI library. You are welcome to explore its full functionality and get technical support from the team when you register for a free 30-day trial. After the trial period e
Indeed, I will refactor the text.

2024-01-11 07:56 UTC, ikoevska approved these changes

2024-01-25 15:49 UTC, dimodi approved these changes

2024-01-25 15:55 UTC, merged