apply seo recommendations
telerik/blazor-docs pull request #2007
Opened 2024-03-29 14:00 UTC by NansiYancheva

Related to [#8914](https://github.com/telerik/blazor/issues/8914)

2024-04-01 14:03 UTC, dimodi approved these changes

2024-04-02 07:47 UTC, yordan-mitev requested changes
Please fix the issues with the `title` and `page_title` fields.

2024-04-02 07:47 UTC, yordan-mitev commented on components/datepicker/overview.md
> +title: Blazor DatePicker Overview | Telerik UI for Blazor
This is the title displayed in the lefthand navigation. It must remain unchanged as it doesn't affect SEO in any way.
```suggestion
title: Overview
```

2024-04-02 07:47 UTC, yordan-mitev commented on components/datepicker/overview.md
>  page_title: Date Picker Overview
This is the SEO title that you could change. However, note the following:
- This title is generated by a template that looks like this: "Blazor" + page_title + - Telerik UI for Blazor.
- The currently rendered title is "Blazor Date Picker Overview - Telerik UI for Blazor".
- There is only one thing that you could change and this is the component name: Date Picker -> DatePicker.
- Changing the separator (from `-` to `|`) is not an option as it is part of the template and we have an agreement with the SEO team that we won't change the separators. If they've requested this change, this is probably a mistake on their part.

```suggestion
page_title: DatePicker Overview
```

2024-04-02 07:47 UTC, yordan-mitev commented on components/dialog/predefined.md
> +title: Blazor Dialogs - Alert, Confirm, Prompt | Telerik UI for Blazor
Do not change this title—it doesn't affect SEO.
```suggestion
title: Predefined Dialogs
```

2024-04-02 07:47 UTC, yordan-mitev commented on components/dialog/predefined.md
>  page_title: Predefined Dialogs - Alert, Confirm, Prompt
Consider the `page_title` (SEO title) template when implementing requirements by the SEO team.
```suggestion
page_title: Dialogs - Alert, Confirm, Prompt
```

2024-04-02 07:47 UTC, yordan-mitev commented on components/dialog/predefined.md
> +Telerik UI for Blazor provides styled substitutes to the standard confirm, alert and prompt dialogs. The Blazor popup messages match the Theme of the components to make it obvious to the user that th
```suggestion
Telerik UI for Blazor provides styled substitutes to the standard confirm, alert, and prompt dialogs. These Blazor popup messages match the Theme of the components to make it obvious to the user that the modal dialog is coming from your application.
```

2024-04-02 07:47 UTC, yordan-mitev commented on components/dialog/predefined.md
>  To use these dialogs, receive a cascading parameter of type `Telerik.Blazor.DialogFactory`. It exposes the methods you can use in your method calls.
When calling one thing different names, we introduce ambiguity, so make sure the reader is still able to understand what we're referring to.
```suggestion
To use these dialogs (popup messages), receive a cascading parameter of type `Telerik.Blazor.DialogFactory`. It exposes the methods you can use in your method calls.
```

2024-04-02 07:47 UTC, yordan-mitev commented on components/menu/navigation.md
> +title: Blazor Navigation Menu | Telerik UI for Blazor
```suggestion
title: Navigation
```

2024-04-02 07:47 UTC, yordan-mitev commented on components/menu/navigation.md
>  page_title: Menu - Navigation
```suggestion
page_title: Navigation Menu
```

2024-04-02 07:47 UTC, yordan-mitev commented on knowledge-base/gauge-pointer-tooltip.md
> +1. Declare an instance of [`Telerik UI for Blazor Tooltip`]({%slug tooltip-overview%}).
Use `monospace` only when something is considered inline code.
```suggestion
1. Declare an instance of `TelerikTooltip` ([Telerik UI for Blazor Tooltip])({%slug tooltip-overview%}).
```

2024-04-11 05:53 UTC, yordan-mitev approved these changes

2024-04-11 16:17 UTC, merged