[Grid] Revamp the Virtual Scrolling article
telerik/blazor-docs pull request #2109
Opened 2024-05-15 13:58 UTC by svdimitr

2024-05-15 14:48 UTC, svdimitr commented
https://github.com/telerik/blazor-docs/pull/2109/commits/9134b115dd5ff41e2eeba9ee6c96cfe189f6eb6a#diff-6dfff5244aefd03df14e4bde914ab8ec7ec2d0480a510d8ceaa0c74fbe6089bcL27 - this is leftover from the previous article, I will delete it tomorrow.

2024-05-16 13:07 UTC, yordan-mitev commented on components/grid/virtual-scrolling.md
> +Virtualization primarily enhances client-side rendering performance and improves the user experience. However, it comes with the trade-off that certain features of the grid are not compatible with it
```suggestion
Virtualization primarily enhances client-side rendering performance and improves the user experience. However, it comes with the trade-off that certain features of the Grid are incompatible with it. An alternative approach is to utilize [regular paging]({%slug components/grid/features/paging%}) combined with [manual data source operations]({%slug components/grid/manual-operations%}) to achieve the desired data retrieval performance.
```

2024-05-16 13:07 UTC, yordan-mitev commented on components/grid/virtual-scrolling.md
> +List of the known limitations of the virtual scrolling feature:
Use a complete sentence instead of a fragment.
```suggestion
These are the known limitations of the virtual scrolling feature:
```

2024-05-16 13:07 UTC, yordan-mitev commented on components/grid/virtual-scrolling.md
> +  * [Documentation: Selection in Grid with virtualized rows]({%slug components/grid/selection/overview%}#selection-in-grid-with-virtualized-rows)
* Use title case capitalization as in the first list item.
* As we are in the docs, you don't need to call this out.
```suggestion
  * [Selection in Grid with Virtualized Rows]({%slug components/grid/selection/overview%}#selection-in-grid-with-virtualized-rows)
```

2024-05-16 13:07 UTC, yordan-mitev commented on components/grid/virtual-scrolling.md
> +  * [Knowledge-Based Article: Virtual Scroll does not show all items]({%slug grid-kb-virtualization-many-records%})
Edit the "Knowledge Base Article" part in the next two anchor links as well.
```suggestion
  * [Knowledge Base Article: Virtual Scroll Does Not Show All Items]({%slug grid-kb-virtualization-many-records%})
```

2024-05-16 14:10 UTC, dimodi requested changes
* The "Setting a value for the" part makes the headings too long and hard to scan when the reader looks in the right column. Consider headings that are just the property names or "Setting Height"
* The same consideration applies for "Knowledge base article: "
* There is too much attention and examples on setting the `Height`. Are there any specifics that customers must keep in mind, which are related to the feature? Do customers have problem with that? The only specific is the relationship between the `Height` and the `PageSize`. In addition, the "relative" example still applies a hard-coded height to the Grid, instead of `GridHeight`.
* There is a need for more clarifications about the `PageSize` - too few items will make skeletons show at all times. Larger `PageSize` will make skeletons appear less frequently, but too large `PageSize` will make the data requests inefficient.
* "The value of the RowHeight must be greater than **or equal to** the height of the **row** that the browser would normally render." Use only "row", because the row height is easier to see in the DOM inspector, and has no padding. You can also mention the exact minimum height number for the default theme just to give an idea, as customers tend to set too small values.
* "Grouping is not supported" is too general and negative statement. You can rephrase like "Grouping is supported only in load-on-demand mode" or "Grouping is supported only if LoadGroupsOnDemand=true" or something like that.
* To make sure the revamp serves the customers, find tickets in which we have linked the Grid virtualization article and see what issues customers had. This can give ideas for further improvements.

2024-05-20 07:50 UTC, svdimitr commented
@dimodi on each point:

* "Setting Height" - I agree it is better - I will change all the headings
* I spoke to Dancho about the length of "Knowledge base article:", the only reason I have left it like that is to be consistent as we tend to write "Documentation:" or "Live Demo:". I can remove the "Knowledge base article:" and leave only the KB title.
* The `Height` is one of the most asked for. People seem to like setting it to `Percentage` and other relative units. I have purposefully made as many examples. With [this commit](https://github.com/telerik/blazor-docs/pull/2109/commits/78253608e4fa7239653b9d21994f6217b0b83a09) I already fixed the value of the Height parameter in the relative example. 
* I have left out this information about the `PageSize` on purpose because there is a KB on the topic, that I have linked.
* I am not sure that I understand the suggestion. 
* I will rename the Grouping not supported bullet, your suggestion is better.
* I have gone through 20 tickets on the topic and the revamp covers these scenarios

2024-05-21 11:29 UTC, yordan-mitev approved these changes

2024-05-28 18:24 UTC, merged