chore(common): fix incorrect file path
telerik/blazor-docs pull request #2495
Opened 2024-11-07 11:43 UTC by ntacheva

2024-11-07 11:58 UTC, Tsvetomir-Hr approved these changes

2024-11-07 14:31 UTC, dimodi requested changes
Are you sure about this? `Pages` is inside `Components` in .NET 8

2024-11-08 08:08 UTC, yordan-mitev approved these changes

2024-11-12 08:13 UTC, dimodi commented on getting-started/web-app.md
> +1. In the `~/Pages/Home.razor` view, add a `TelerikButton` component.
```suggestion
1. In `.../Pages/Home.razor` in the server or client project, add a `TelerikButton` component.
```

2024-11-12 08:13 UTC, dimodi approved these changes

2024-11-12 08:20 UTC, merged