docs(scheduler):resource grouping documentation added
telerik/blazor-docs pull request #363
Opened 2021-06-16 19:59 UTC by xristianstefanov

- Added Grouping in the Scheduler documentation
- New sections for Resource Grouping in all the available views

2021-06-17 18:26 UTC, marin-bratanov commented on components/scheduler/views/day.md
> +@[template](/_contentTemplates/scheduler/views.md#code-snippet)
Use a more descriptive heading for the template

2021-06-17 18:26 UTC, marin-bratanov commented on components/scheduler/grouping.md
> +title: Grouping
I recommend you add to the url and various title the keyword "resource grouping"

2021-06-18 18:28 UTC, marin-bratanov commented
I recommend you rename the `#code-snippet` name in `(/_contentTemplates/scheduler/views.md#code-snippet)` to make it more meaningful. Will try to build and review in more detail over the weekend.

2021-06-19 10:13 UTC, marin-bratanov requested changes
The OnInitializedAsync in the component should not have to generate resources, the service should provide them. Make sure that code is cleaned up.

Rename the headings for resource grouping in the inidividual view articles to include the view name (e.g. "Resource Grouping in the Day View") as that's the first examples people will see when landing on the Resource Grouping page.

In the Resource Grouping article, consider moving the links to the four views examples in the basics section - so people have seen one example and are familiar with the new tag and its settings before looking at rather complex code.

Add a screenshot for grouping by multiple resources. In fact, consider making headings for them, it is a nice thing to point out to people. You can have three sections - Basics, Single resource grouping (that also links to individual views examples) and Multipel Resource Grouping.

2021-06-21 14:08 UTC, dimodi commented on components/scheduler/views/day.md
> +You can configure the Day view to display events that are [grouped]({%slug scheduler-resource-grouping%}) by a resource.
better SEO with more keywords in the link:

```suggestion
You can configure the Day view to display events that are [grouped by a resource]({%slug scheduler-resource-grouping%}).
```

2021-06-21 14:08 UTC, dimodi commented on components/scheduler/views/month.md
> +You can configure the Month view to display events that are [grouped]({%slug scheduler-resource-grouping%}) by a resource.
```suggestion
You can configure the Month view to display events that are [grouped by a resource]({%slug scheduler-resource-grouping%}).
```

2021-06-21 14:09 UTC, dimodi commented on components/scheduler/views/multiday.md
> +You can configure the MultiDay view to display events that are [grouped]({%slug scheduler-resource-grouping%}) by a resource.
```suggestion
You can configure the MultiDay view to display events that are [grouped by a resource]({%slug scheduler-resource-grouping%}).
```

2021-06-21 14:09 UTC, dimodi commented on components/scheduler/views/week.md
> +You can configure the MultiDay view to display events that are [grouped]({%slug scheduler-resource-grouping%}) by a resource.
```suggestion
You can configure the MultiDay view to display events that are [grouped by a resource]({%slug scheduler-resource-grouping%}).
```

2021-06-21 14:10 UTC, dimodi commented on components/scheduler/resource-grouping.md
> +description: Resource Grouping in the Scheduler for Blazor.
Use different keywords or different grammar forms:

```suggestion
description: Group Resources in the Scheduler for Blazor.
```

2021-06-21 14:11 UTC, dimodi commented on components/scheduler/resource-grouping.md
> +The feature allows grouping Scheduler views by one or more resources. All available supported views: `Day`, `Week`, `MultiDay` and `Month` can render both `horizontal` and `vertical` grouping.
We group events, not views, right?

```suggestion
The feature allows grouping Scheduler events by one or more resources. All available supported views: `Day`, `Week`, `MultiDay` and `Month` can render both `horizontal` and `vertical` grouping.
```

2021-06-21 14:12 UTC, dimodi commented on components/scheduler/resource-grouping.md
> +To configure the group rendering, define a dedicated settings tag, called a `SchedulerGroupSettings` inside the `SchedulerSettings` tag.
Removing self-explanatory details.

```suggestion
To configure the group rendering, define the `SchedulerGroupSettings` tag inside the `SchedulerSettings` tag.
```

2021-06-21 14:13 UTC, dimodi commented on components/scheduler/resource-grouping.md
> +* `Resources(List<string>)` - provides a list of one or more resource names, which will be used to group the scheduler by.
```suggestion
* `Resources(List<string>)` - provides a list of one or more resource names, which will be used to group the events.
```

2021-06-21 14:14 UTC, dimodi commented on components/scheduler/resource-grouping.md
> +* `Orientation(SchedulerGroupOrientation)` - has two values: `Horizontal(default)` and `Vertical`. Determines the direction in which the resource tables are rendered.
```suggestion
* `Orientation(SchedulerGroupOrientation)` - has two values: `Horizontal` (default) and `Vertical`. Determines the direction in which the resource tables are rendered.
```

2021-06-21 14:14 UTC, dimodi approved these changes

2021-06-22 05:12 UTC, marin-bratanov approved these changes
approving, I have not had time to check

2021-06-22 06:24 UTC, merged