Add Carousel documentation
telerik/blazor-docs pull request #459
Opened 2021-09-02 14:13 UTC by dimodi

2021-09-03 16:15 UTC, marin-bratanov requested changes
Also, I highly recommend a responsive example (even if a KB).

2021-09-03 16:15 UTC, marin-bratanov commented on components/carousel/events.md
> +This article describes the available events of the Telerik Carousel for Blazor.
Add a bullet list with the event name - even if it is only one, so people can see what's available at a glance.

2021-09-03 16:15 UTC, marin-bratanov commented on components/carousel/overview.md
> +````CSHTML
Consider making an example with a model as it will feel more real-life to people.

2021-09-03 16:15 UTC, marin-bratanov commented on components/carousel/template.md
> +The nested `<Template>` tag of the `<TelerikCarousel>` represents a standard [`RenderFragment`](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/templated-components).
Add a sentence to describe what you do with that template, and, more importantly, that it is mandatory.

2021-09-07 13:21 UTC, dimodi commented
Improvements applied. I will think about a responsive example and add it as a KB.

2021-09-07 15:18 UTC, merged