feat(timeline): timeline view for scheduler
telerik/blazor-docs pull request #464
Opened 2021-09-07 13:55 UTC by svdimitr

2021-09-08 05:30 UTC, marin-bratanov requested changes

2021-09-08 05:30 UTC, marin-bratanov commented on components/scheduler/views/timeline.md
> +description: Day View in the Scheduler for Blazor.
wrong text in the description field

2021-09-08 10:04 UTC, svdimitr commented on components/scheduler/views/timeline.md
> +description: Day View in the Scheduler for Blazor.
Thank you, corrected it

2021-09-09 19:11 UTC, marin-bratanov approved these changes

2021-09-11 17:31 UTC, merged