kb(window):added kb for chat popup
telerik/blazor-docs pull request #582
Opened 2021-11-18 07:26 UTC by xristianstefanov

- Added KB for implementing a chat popup with the modal window
- Responsive chat

2021-11-18 07:58 UTC, marin-bratanov reviewed
I strongly advise against such a KB. A Chat component has a huge amount of moving parts and other functionality people expect and need, and this will not cover their needs. If people have the chat component to put in the window, the chances are that this component already has its own functionality to create its own popup.

2021-11-18 08:05 UTC, xristianstefanov commented
> I strongly advise against such a KB. A Chat component has a huge amount of moving parts and other functionality people expect and need, and this will not cover their needs. If people have the chat component to put in the window, the chances are that this component already has its own functionality to create its own popup.

The idea is to have an example for the clients that want to just minimize the modal window as a chat, not a real alternative to the chat component. The feature request for the Chat component https://feedback.telerik.com/blazor/1517233-conversational-ui-chat will stay on "Unplanned".

2021-11-22 08:26 UTC, dimodi commented
We can remove the chat-related keywords and focus on the minimize behavior of the Window only.

2021-11-22 08:42 UTC, xristianstefanov commented
> We can remove the chat-related keywords and focus on the minimize behavior of the Window only.

I agree here to focus on the minimize behavior.

2021-11-26 13:31 UTC, dimodi commented on knowledge-base/window-modal-minimize-popup.md
> +tags: window,modal,chat,popup,collapse,minimize
```suggestion
tags: window,modal,popup,collapse,minimize
```

2021-11-26 13:33 UTC, dimodi commented on knowledge-base/window-modal-minimize-popup.md
> +    .messanger {
```suggestion
    .minimized {
```

2021-11-26 13:33 UTC, dimodi commented on knowledge-base/window-modal-minimize-popup.md
> +        <div @onclick="@( _ => isModalVisible = true )" class="messanger"><strong>@Title[0]</strong></div>
```suggestion
        <div @onclick="@( _ => isModalVisible = true )" class="minimized"><strong>@Title[0]</strong></div>
```

2021-11-26 13:36 UTC, dimodi commented
It will be better to minimize the Window instance itself, instead of a custom <div>. Change the size and position attribute values.

The huge benefit will be that the user will be able to drag the minimized Window to a random location on the screen. We can hide/show the Window content with custom CSS.

2021-11-26 13:37 UTC, dimodi requested changes
It will be better to minimize the Window instance itself, instead of showing a custom div. Change the Window size and position attribute values, remember the old values, and then restore them.

The huge benefit will be that the user will be able to drag the minimized Window to a random location on the screen. We can hide/show the Window content with custom CSS.

2021-11-29 19:27 UTC, marin-bratanov commented
The downside will be that with responsive layouts the minimized window will fly all over the place if the user resizes the browser.
Ideally, this is to be solved with something like position:fixed for the minimized window, but you lose draggingthen.
Even more ideally, a feature lets it minimize to a zone/container that you can define in your layout, but that's feasible in kendo and webforms where youmanipulate the domdirectly (see MinimizeZonID in Webforms which enables [this](https://demos.telerik.com/aspnet-ajax/window/examples/radwindowandmdi/defaultcs.aspx)). I hope you are starting to see why I am opposed to this article :) It covers too little, and is too complex already, to be usable in a real-world app.

2021-12-08 08:38 UTC, dimodi approved these changes

2021-12-08 08:39 UTC, merged