[3.2] docs(textarea): Revamped TextArea Overview
telerik/blazor-docs pull request #829
Opened 2022-03-10 16:00 UTC by xristianstefanov

2022-03-25 13:02 UTC, dimodi commented on components/textarea/overview.md
>  The Telerik <a href ="https://www.telerik.com/blazor-ui/textarea" target="_blank">Blazor TextArea component</a> is a highly customizable multi-line text input area. It provides features like auto res
```suggestion
The Telerik <a href ="https://www.telerik.com/blazor-ui/textarea" target="_blank">Blazor TextArea component</a> is a highly customizable multi-line text input area. It provides features like auto resizing based on the user input and [events]({%slug textarea-events%}) to respond to user actions.
```

2022-03-25 13:04 UTC, dimodi commented on components/textarea/overview.md
> +3. (optional) Set the `Label` and `AutoSize` properties to adjust the TextArea height based on the user input.
Label ??

2022-03-25 13:07 UTC, dimodi commented on components/textarea/overview.md
> +The Blazor TextArea fires blur and value change events for further customizing its behavior. [Read more about the Blazor TextArea events]({%slug textarea-events%}).
```suggestion
The Blazor TextArea fires **blur** and value **change** events to respond to user actions. [Read more about the Blazor TextArea events]({%slug textarea-events%}).
```

2022-03-25 13:08 UTC, dimodi commented on components/textarea/overview.md
> +| `ValidateOn` | `ValidationEvent` | Configures the event that will trigger validation (if validation is enabled). Read more at [Validation Modes for Simple Inputs]({%slug common-features/input-valid
default value

2022-03-25 13:08 UTC, dimodi requested changes
Fix basic example and instructions. Provide ValidateOn default value.

2022-03-25 15:56 UTC, xristianstefanov commented on components/textarea/overview.md
> +3. (optional) Set the `Label` and `AutoSize` properties to adjust the TextArea height based on the user input.
It's forgotten there..

2022-03-28 11:42 UTC, dimodi approved these changes

2022-03-28 11:44 UTC, merged