[3.3] Scrollable Tabs
telerik/blazor-docs pull request #921
Opened 2022-04-29 09:43 UTC by svdimitr

2022-04-29 15:44 UTC, dimodi commented on components/tabstrip/scrollable-tabs.md
> +    <TabStripTab Title="First">
Generate the tabs with a loop to make the example simpler.

2022-04-29 15:45 UTC, dimodi commented on components/tabstrip/scrollable-tabs.md
> +slug: tabstrip-scroll-tabs
scroll-tabs may be harder to remember and use without checking. Why not use scrollable-tabs, as the article title?

2022-04-29 15:48 UTC, dimodi commented on components/tabstrip/scrollable-tabs.md
> +By default, if the accumulative width or height of the tabs in the TabStrip exceed the width or height of the browser a browser-level scrollbar will appear.
Consider a simpler version. It's "cumulative" by the way.
```suggestion
If the TabStrip dimensions exceed the width or height of the page, a browser-level scrollbar will appear. 
```

2022-04-29 15:49 UTC, dimodi commented on components/tabstrip/scrollable-tabs.md
> +To scroll the tabs only, set the `Scrollable` bool parameter of the TabStrip to `true` (defaults to `false`). You should also set the `Width` (for tabs with [Position]({%slug tabstrip-tabs-position%}
Can be a list of 3 steps as well.

2022-04-29 15:52 UTC, dimodi commented on components/tabstrip/overview.md
>  * [Features](#features)
We should list the features themselves and remove the Features heading. See /wiki/Docs-Overview-Page-Template in the private repo.

2022-05-09 10:21 UTC, dimodi requested changes
Consider these -
* article slug's grammar to match the article's title, for easier usage
* generate the tabs with a loop to make the code snippets short and simple
* replace the Features heading with the actual features - https://github.com/telerik/blazor/wiki/Docs-Overview-Page-Template

2022-05-09 19:29 UTC, jivanova approved these changes

2022-05-09 19:29 UTC, merged