docs(common):UI for Blazor in Hybrid Apps
telerik/blazor-docs pull request #998
Opened 2022-06-17 16:47 UTC by ntacheva

2022-06-20 03:19 UTC, Stamo-Gochev commented on hybrid-blazor-apps.md
> +At the time of writing, this technology is in preview phase, and there may be difficulties and missing features. A few examples include:
This is no longer true as MAUI is now officially supported as well as the webviews.

2022-06-20 03:19 UTC, Stamo-Gochev commented on hybrid-blazor-apps.md
> +* There are reports of difficulties getting MAUI to work. It is early days for it yet, and you need to ensure you can run it first, before adding Blazor to the mix.
```suggestion
* There are reports of difficulties getting MAUI to work. It is early days for it yet, and you need to ensure you can run it first, before adding Blazor to the mix.
```
This is supposed to be fixed with the official release of MAUI.

2022-06-21 08:46 UTC, dimodi commented on hybrid-blazor-apps.md
> +>tip Explore the [Hybrid Blazor Apps (Blazor Web apps running in WinForms, WPF, MAUI)](https://github.com/telerik/blazor-ui/tree/master/common/hybrid-blazor-apps) sample app.
The samples apps are several. Consider two sentences instead of brackets.

2022-06-21 08:47 UTC, dimodi commented on hybrid-blazor-apps.md
> +Prior to adding the Telerik components, you need to make sure you can run the corresponding technology stack and the basic Hybrid Blazor WebView in it.
"you can run" may sound a bit condescending.

```suggestion
Prior to adding the Telerik components, ensure the corresponding technology stack is setup and the basic Hybrid Blazor WebView runs as expected in it.
```

2022-06-21 08:50 UTC, dimodi commented on hybrid-blazor-apps.md
> +@using Telerik.Blazor.Services
This line is not necessary in Blazor apps. Is the addition here on purpose? If yes, we can mention why.

2022-06-21 08:53 UTC, dimodi commented on hybrid-blazor-apps.md
> +After completing the above steps, you will be able to add your desired Telerik Blazor components in the app as in a native Blazor app. Explore the available UI for Blazor components and their feature
We don't need "after completing..." in a numbered list. 
```suggestion
Add your desired Telerik Blazor components in the app as in a native Blazor app. Explore the available UI for Blazor components and their features in our [live demos](https://demos.telerik.com/blazor-ui).
```

2022-06-21 08:57 UTC, dimodi commented on hybrid-blazor-apps.md
> +You can now run the application in the expected for the technology stack way, following the corresponding instructions for how to run the app. Here are the related resources for ease of access:
We mention that the developer should be familiar with the technology stack from the beginning, so this part might be unnecessary. Or we should move it up. 

```suggestion
You can now run the hybrid application. Refer to the following resources for each technology stack:
```

2022-06-21 08:58 UTC, dimodi commented on hybrid-blazor-apps.md
> +
```suggestion
```

2022-06-21 08:59 UTC, dimodi commented on hybrid-blazor-apps.md
> +* There is no debugging protocol exposed for the webview, so inspecting content and debugging is difficult.
Do we have a suitable link here? If not, it's better to remove the second part of the sentence.

```suggestion
* There is no debugging protocol exposed for the webview, so inspecting content and debugging is difficult.
```

2022-06-21 09:02 UTC, dimodi commented on hybrid-blazor-apps.md
> +* Access to native APIs from the Blazor Web app code is still to be exposed by the framework - at the moment you have to write your own calls to services and code from the native app that you need to
```suggestion
* The Blazor web app code cannot make calls to native APIs. This feature yet to be exposed by the framework. At the moment, you have to write your own calls to services and native app code that you need to explicitly expose.
```

2022-06-21 09:04 UTC, dimodi commented on hybrid-blazor-apps.md
> +* The WebView is not on the [list of officially supported browsers by Telerik UI for Blazor]({%slug browser-support%}). It has its specifics and differences from a standalone browser, and the hybrid
```suggestion
* The WebView is not on the [list of officially supported browsers by Telerik UI for Blazor]({%slug browser-support%}). It has its specifics and differences from a standalone browser. The hybrid Blazor app integration should be considered a proof-of-concept for the time being. We will monitor the framework maturity and consider adding the webview to the list of supported environments.
```

2022-06-21 09:05 UTC, dimodi commented on hybrid-blazor-apps.md
> +* Running MAUI apps might require developer mode to be [enabled](https://stackoverflow.com/questions/36324300/ensure-that-target-device-has-developer-mode-enabled-could-not-obtain-a-develop).
```suggestion
* Running MAUI apps may require [developer mode to be enabled](https://stackoverflow.com/questions/36324300/ensure-that-target-device-has-developer-mode-enabled-could-not-obtain-a-develop).
```

2022-06-21 09:07 UTC, dimodi requested changes
Use shorter sentences, less passive voice, and less subordinate clauses. Use correct heading hierarchy.

2022-06-21 13:13 UTC, dimodi approved these changes

2022-06-21 13:15 UTC, merged